repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: "v14.0.6"
    hooks:
      - id: clang-format

  - repo: https://github.com/cpplint/cpplint
    rev: "1.6.0"
    hooks:
      - id: cpplint
