name: PlatformIO CI

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3.1.4
      - run: pip install -U platformio

  check:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - run: pio check --skip-packages

  precommit:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - run: pip install pre-commit
      - run: pre-commit run --all-files

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - run: pio run
      - uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: |
            .pio/build/adafruit_feather_m0/firmware.bin
